#java -jar xx.jar --server.port=8082
server:
   port: 8083
   context-path: /basic
spring:
#   profiles: dev_env
  #注册到eureka上面的应用名称
   application:
      name: springboot-staticfile
yunfeng.name: yf
yunfeng.age: 26
yf.path: d:/yf/
#默认使用logback日志
logging:
  file: D:/test.log
logging.level.org.springframework.web: DEBUG

